[package]
name = "iris-onnx"
version = "0.11.0"
edition = "2021"

description = "ONNX support for Candle"
repository = "https://github.com/fern-robotics/iris"
keywords = ["blas", "tensor", "machine-learning"]
categories = ["science"]
license = "MIT OR Apache-2.0"

[dependencies]
iris-core = { path = "../iris-core", package = "iris-core", version = "0.11.0" }
iris-nn = { path = "../iris-nn", version = "0.11.0" }
prost = "0.14.1"

[build-dependencies]
prost-build = "0.14.1"

[dev-dependencies]
anyhow = { version = "1", features = ["backtrace"] }
clap = { version = "4.5.49", features = ["derive"] }
